image: node

stages:
  - open
  - test
  - build
  - publish

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .yarn
    - .jest

before_script:
  - yarn

open_merge_request:
  image: registry.gitlab.com/hmajid2301/gitlab-auto-merge-request
  stage: open
  before_script: []
  variables:
    GIT_STRATEGY: none
    REMOVE_BRANCH_AFTER_MERGE: "true"
    SQUASH: "true"
    TARGET_BRANCH: "master"
  except:
    - master
    - production
  script:
    - merge-request.sh

lint:
  stage: test
  before_script:
    - yarn
  script:
    - yarn lint

lint:critical:
  stage: test
  script:
    - yarn lint-critical

typescript-compilation:
  stage: test
  allow_failure: true
  script:
    - yarn tsc-test

unit-tests:
  stage: test
  script:
    - yarn jest

publish_app:
  stage: publish
  only:
    - /^release/.*$/
  script:
    - expo login -u $PROJECT_USERNAME -p $PROJECT_PASSWORD
    - expo --non-interactive publish
