image: node:8

stages:
  - pre
  - test
  - build
  - publish
  - post

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - chmod +x util/generateDotEnv.sh
  - ./util/generateDotEnv.sh > .env
  - yarn

create:merge-request:
  image: registry.gitlab.com/gitlab-automation-toolkit/gitlab-auto-mr
  stage: pre
  before_script: []
  except:
    - production
    - master
  script:
    - gitlab_auto_mr -t master -c WIP -d ./.gitlab/merge_request/merge_request.md -r -s --use-issue-name 

lint:
  stage: test
  only:
    - merge_request
  script:
    - yarn lint

lint:code-formatter:
  stage: test
  only:
    - merge_request
  script:
    - yarn code-formatter-check

lint:compiler:
  stage: test
  only:
    - merge_request
  script:
    - yarn compiler-check

tests:unit:
  stage: test
  only:
    - merge_request
  script:
    - yarn tests --silent 

test:coverage:
  stage: test
  only:
    - merge_request
    - master
  script:
    - yarn coverage --silent
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

test:android:lint:
  stage: test
  image: reactnativecommunity/react-native-android
  only:
    - /^release/.*$/
  before_script:
    - cd android
    - mv $FIREBASE_GOOGLE_SERVICES app/google-services.json
  script:
    - yarn android-lint

test:android:assemble:
  stage: test
  image: reactnativecommunity/react-native-android
  only:
    - /^release/.*$/
  before_script:
    - cd android
    - mv $FIREBASE_GOOGLE_SERVICES app/google-services.json
  script:
    - yarn android-debug 

build:android:package:
  stage: build
  image: reactnativecommunity/react-native-android
  only:
    - /^release/.*$/
  script:
    - export CHANGELOG = $("cat CHANGELOG.md")
    - const changelog = `$CHANGELOG`;\n export default changelog;
    - cd android
    - mv $FIREBASE_GOOGLE_SERVICES app/google-services.json
    - base64 -d $ANDROID_KEYSTORE > app/stegappasaurus.keystore
    - echo "MYAPP_RELEASE_STORE_FILE=stegappasaurus.keystore" > gradle.properties
    - echo "MYAPP_RELEASE_STORE_PASSWORD=$ANDROID_KEYSTORE_PASSWORD" >> gradle.properties
    - echo "MYAPP_RELEASE_KEY_ALIAS=$ANDROID_KEYSTORE_ALIAS" >> gradle.properties
    - echo "MYAPP_RELEASE_KEY_PASSWORD=$ANDROID_KEYSTORE_KEY_PASSWORD" >> gradle.properties
    - yarn react-native link
    - mv $PLAY_STORE_JSON /tmp/play-store-key.json
    - yarn android-bundle
    - cp react.gradle ../node_modules/react-native/
    - yarn android-build-apk
  artifacts:
    paths:
    - ./android/app/build/outputs/

publish:release:
  image: registry.gitlab.com/gitlab-automation-toolkit/gitlab-auto-release
  stage: post
  only:
    - /^release/.*$/
  before_script: []
  variables:
    GIT_STRATEGY: none
  script:
    - gitlab_auto_release -c CHANGELOG.md \
      -d "This was auto-generated by the gitlab-auto-release tool, https://gitlab.com/gitlab-automation-toolkit/gitlab-auto-release." \
        --link-assets
