image: node:10.15.3

stages:
  - pre
  - test
  - build
  - publish

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - chmod +x util/generateDotEnv.sh
  - ./util/generateDotEnv.sh > .env
  - yarn
  - cd src/services && yarn --ignore-engines && cd ../..

open-merge-request:
  image: registry.gitlab.com/hmajid2301/gitlab-auto-mr
  stage: pre
  before_script: []
  variables:
    REMOVE_BRANCH_AFTER_MERGE: "true"
    SQUASH: "true"
    AUTO_MERGE: "true"
    TARGET_BRANCH: "master"
    COMMIT_PREFIX: "WIP"
    USE_ISSUE_NAME: "true"
  except:
    - master
    - production
  script:
    - export DESCRIPTION="$(< util/MR.md)"
    - gitlab_auto_mr

lint:
  stage: test
  script:
    - yarn lint

lint:code-formatter:
  stage: test
  script:
    - yarn lint:code-formatter

lint:compiler:
  stage: test
  script:
    - yarn lint:compiler

tests:unit:
  stage: test
  script:
    - yarn tests

test:coverage:
  stage: test
  only:
    - master
  script:
    - yarn coverage
  coverage: '/^All files\s+\|\s+\d+\.*\d*\s+\|\s*(\d+\.*\d*)/'

publish:image-ttl:
  stage: publish
  image: google/cloud-sdk:slim
  only:
    - master
  before_script:
    - echo $FIREBASE_KEY_FILE >> /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  script:
    - gsutil lifecycle set src/services/ImagesTTL.json gs://stegappasaurus.appspot.com/

publish:firebase-functions:
  stage: publish
  only:
    - master
  script:
    - yarn run deploy-services -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_TOKEN > output
    - tail -n +4 output

publish:app:
  stage: publish
  only:
    - /^release/.*$/
  script:
    - yarn expo login -u $PROJECT_USERNAME -p $PROJECT_PASSWORD
    - yarn expo --non-interactive publish
