image: node:8

stages:
  - pre
  - test
  - build
  - publish
  - post

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - src/services/node_modules

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - chmod +x util/generateDotEnv.sh
  - ./util/generateDotEnv.sh > .env
  - yarn
  - cd src/services
  - yarn
  - cd ../..

open-merge-request:
  image: registry.gitlab.com/hmajid2301/gitlab-auto-mr
  stage: pre
  before_script: []
  variables:
    REMOVE_BRANCH_AFTER_MERGE: "true"
    SQUASH: "true"
    AUTO_MERGE: "true"
    TARGET_BRANCH: "master"
    COMMIT_PREFIX: "WIP"
    USE_ISSUE_NAME: "true"
    DESCRIPTION: ".gitlab/merge_request/merge_request.md"
  except:
    - master
    - production
  script:
    - gitlab_auto_mr

lint:
  stage: test
  script:
    - yarn lint

lint:code-formatter:
  stage: test
  script:
    - yarn code-formatter-check

lint:compiler:
  stage: test
  script:
    - yarn compiler-check

tests:unit:
  stage: test
  script:
    - yarn tests

test:coverage:
  stage: test
  only:
    - master
  script:
    - yarn coverage
  coverage: '/^All files\s+\|\s+\d+\.*\d*\s+\|\s*(\d+\.*\d*)/'

publish:firebase-functions:
  stage: publish
  only:
    - master
  script:
    - yarn run deploy-services -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_TOKEN