image: node:alpine

stages:
  - open_mr
  - test
  - build
  - publish

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.npm
    - .jest

before_script:
  - yarn

Open Merge Request:
  image: tmaier/gitlab-auto-merge-request
  stage: open_mr
  before_script: []
  variables:
    GIT_STRATEGY: none
  except:
    - master
    - production
  script:
    - merge-request.sh

lint:
  stage: test
  only:
    - master
  before_script:
    - yarn
  script:
    - yarn lint

lint:critical:
  stage: test
  only:
    - master
  script:
    - yarn lint-critical

typescript-compilation:
  stage: test
  only:
    - master
  script:
    - yarn tsc-test

unit-tests:
  stage: test
  only:
    - master
  script:
    - yarn jest

publish_app:
  stage: publish
  only:
    - /^release/.*$/
  script:
    - expo login -u $PROJECT_USERNAME -p $PROJECT_PASSWORD
    - expo --non-interactive publish
