image: node:8

stages:
  - pre
  - test
  - build
  - publish
  - post

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - src/services/node_modules

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - chmod +x util/generateDotEnv.sh
  - ./util/generateDotEnv.sh > .env
  - yarn


create:merge-request:
  image: registry.gitlab.com/hmajid2301/gitlab-auto-mr
  stage: pre
  before_script: []
  variables:
    REMOVE_BRANCH_AFTER_MERGE: "true"
    SQUASH: "true"
    AUTO_MERGE: "true"
    TARGET_BRANCH: "master"
    COMMIT_PREFIX: "WIP"
    USE_ISSUE_NAME: "true"
    DESCRIPTION: ".gitlab/merge_request/merge_request.md"
  except:
    - master
    - production
    - tags
  script:
    - gitlab_auto_mr

lint:
  stage: test
  script:
    - cd src/services && yarn && cd ../..
    - yarn lint

lint:code-formatter:
  stage: test
  script:
    - cd src/services && yarn && cd ../..
    - yarn code-formatter-check

lint:compiler:
  stage: test
  script:
    - cd src/services && yarn && cd ../..
    - yarn compiler-check

tests:unit:
  stage: test
  script:
    - cd src/services && yarn && cd ../..
    - yarn tests

test:coverage:
  stage: test
  only:
    - master
  script:
    - cd src/services && yarn && cd ../..
    - yarn coverage
  coverage: '/^All files\s+\|\s+\d+\.*\d*\s+\|\s*(\d+\.*\d*)/'

test:android:lint:
  stage: test
  image: reactnativecommunity/react-native-android
  only:
    - /^release/.*$/
  before_script:
    - cd android
    - mv $FIREBASE_GOOGLE_SERVICES app/google-services.json
  script:
    - yarn android-lint

test:android:assemble:
  stage: test
  image: reactnativecommunity/react-native-android
  only:
    - /^release/.*$/
  before_script:
    - cd android
    - mv $FIREBASE_GOOGLE_SERVICES app/google-services.json
  script:
    - yarn android-debug 

build:android:package:
  stage: build
  image: reactnativecommunity/react-native-android
  only:
    - /^release/.*$/
  script:
    - rm -r src/services
    - cd android
    - mv $FIREBASE_GOOGLE_SERVICES app/google-services.json
    - base64 -d $ANDROID_KEYSTORE > app/stegappasaurus.keystore
    - echo "MYAPP_RELEASE_STORE_FILE=stegappasaurus.keystore" > gradle.properties
    - echo "MYAPP_RELEASE_STORE_PASSWORD=$ANDROID_KEYSTORE_PASSWORD" >> gradle.properties
    - echo "MYAPP_RELEASE_KEY_ALIAS=$ANDROID_KEYSTORE_ALIAS" >> gradle.properties
    - echo "MYAPP_RELEASE_KEY_PASSWORD=$ANDROID_KEYSTORE_KEY_PASSWORD" >> gradle.properties
    - yarn react-native link
    - mv $PLAY_STORE_JSON /tmp/play-store-key.json
    - yarn android-bundle
    - cp react.gradle ../node_modules/react-native/
    - yarn android-build-apk
  artifacts:
    paths:
    - ./android/app/build/outputs/

publish:firebase:functions:
  stage: publish
  only:
    - master
    - tags
  script:
    - cd src/services && yarn && cd ../..
    - yarn run deploy-services -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_TOKEN

publish:firebase:env:
  stage: publish
  only:
    - master
    - tags
  script:
    - yarn run firebase functions:config:set env.production=true

publish:release:
  image: registry.gitlab.com/hmajid2301/gitlab-auto-release
  stage: post
  only:
    - /^release/.*$/
  before_script: []
  variables:
    DESCRIPTION: "This was auto-generated by the gitlab-auto-release tool, https://gitlab.com/hmajid2301/gitlab-auto-release."
    CHANGELOG: CHANGELOG.md
  script:
    - gitlab_auto_release
