image: node

stages:
  - open
  - test
  - build
  - publish

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - yarn

open_merge_request:
  image: registry.gitlab.com/hmajid2301/gitlab-auto-mr
  stage: open
  before_script: []
  variables:
    GIT_STRATEGY: none
    REMOVE_BRANCH_AFTER_MERGE: "true"
    SQUASH: "true"
    AUTO_MERGE: "true"
    TARGET_BRANCH: "master"
    COMMIT_PREFIX: "WIP"
  except:
    - master
    - production
  script:
    - gitlab_auto_mr

lint:
  stage: test
  before_script:
    - yarn
  script:
    - yarn lint

lint:critical:
  stage: test
  script:
    - yarn lint-critical

lint:tsc:
  stage: test
  allow_failure: true
  script:
    - yarn lint-tsc

unit-tests:
  stage: test
  script:
    - yarn tests

coverage:
  stage: test
  only:
    - master
  script:
    - yarn coverage
  coverage: '/^All files\s+\|\s+\d+\.*\d*\s+\|\s*(\d+\.*\d*)/'

publish_app:
  stage: publish
  only:
    - /^release/.*$/
  script:
    - expo login -u $PROJECT_USERNAME -p $PROJECT_PASSWORD
    - expo --non-interactive publish
