version: "3.5"

services:
  expo_android:
    container_name: expo_android
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ${PWD}/:/opt/Stegappasaurus/
