export const RESET_PREFERENCES = "RESET_PREFERENCES";
export const TOGGLE_AUTOMATIC_THEME = "TOGGLE_AUTOMATIC_THEME";
export const TOGGLE_DARK_THEME = "TOGGLE_DARK_THEME";
export const TOGGLE_PRIMARY_COLOR = "TOGGLE_PRIMARY_COLOR";
