#!/usr/bin/env bash

cat  << EOF
ADB_IP=NA
REACT_NATIVE_PACKAGER_HOSTNAME=NA
CAT_API_KEY=${CAT_API_KEY}
FIREBASE_API_KEY=${FIREBASE_API_KEY}
FIREBASE_API_URL=${FIREBASE_API_URL}
SENTRY_API_TOKEN=${SENTRY_API_TOKEN}
SENTRY_PUBLIC_DSN=${SENTRY_PUBLIC_DSN}
EOF