#!/usr/bin/env bash

cat  << EOF
ADB_IP=NA
BUGSNAG_API_KEY=${BUGSNAG_API_KEY}
CAT_API_KEY=${CAT_API_KEY}
FIREBASE_API_URL=${FIREBASE_API_URL}
REACT_NATIVE_PACKAGER_HOSTNAME=NA
TIMBER_API_KEY=${TIMBER_API_KEY}
TIMBER_SOURCE_ID=${TIMBER_SOURCE_ID}
EOF
